language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sori/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sori/react-test npm run test

after_success:
  - docker build -t sori/multi-client ./client
  - docker build -t sori/multi-nginx ./nginx
  - docker build -t sori/multi-server ./server
  - docker build -t sori/multi-worker ./worker
  # Lo in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sori/multi-client
  - docker push sori/multi-nginx
  - docker push sori/multi-server
  - docker push sori/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-228194064843
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: I5fYBTq2knttmPYpeGo39Cq/epOlgghmBje7pxh9iKY6ehYC9T/L8cYIG1qz3gNwZgm1R6dmo7hR7cpCuDPMx/5TUoHhAHBYYX3odpl6Xx3vuqd9S2w635PmyLPjIciGfYhnxqjJNkinR5DPlI2jADLPBPTFSAuGO+ca/zkUkN4sG2mp3VO+3mZ1HB9pVXJtKVpUr51yZ6vajLHCr3Db74jg+uXzzMXA8rC9TvCtY2RWKtGl1/A47L4NaxYLwQIe58QMMXAsDaf7S/Dj8CmhvyDnYxQAAWjoPnaSFPSKdT58YuV8QTg121cnZ+t5yT+TNlslDPDChWt2ORq6jK4rmUEdzH6fN5ZQBaewJJnvBxV37ana9IYsjo5eH4d4Ws6+rUTotLQb3/gnXmCa6JNWs5OaCBcSnkO1XYaEOZOdKrI0pMp40viMnpI0HzXIEgRTIWTDg4NXTzH9Y4JOApdZKvBNUwsJ7XqbArV+zDw0C6pDIxo0eo+I+Vj5WHIoHzsIxyPYpsoEDhKvubLydASKe9V1/22/L+qCwdGB8OdoHC4LM/EMgTxAbXg3h9wjjrV/HM7X8XXcI9ySzdqkH29CTjj6PmCBPr2jL3qLQ6V3QcgPVGLdAQqyrpgmP04n5YvZWyDh1vKoJOw1vhZyBud/tdQma16NniwTbcj4GwyEllE=
  secret_access_key:
    secure: GZV0nvwix2h8RiUXSrqA5cBJxYSFclPFkh0o+cBnjjI5z0QPIugHBa/aq/oXWPu+ISVvbIHBEaKxcErTvtoUg6MylTxa8yTCU5RTbXn2F/UD4UqyZ91gCgG1lHJ4VvSi3qExkQO52u4xNLrgktfZ0RMvSaYnewJbAG60ILTddKqX7hF6GqQ1kjyhgaSdIeGji3Bx83u1uRehu/lCQGZ8n4axrqkklgqaD6E7jbuNkmzRy9w50+QWQHU5+W8CBQwzyBVElTnqYocXPAqQizcwoZu0aPtKyqmS8nRDg8NH1seEKhrsRhhlyHb4opQQk386DhCvPxs1aNh1+VO24KHPTJa6qH1e3obDxDcPvldCO9lcdjUF8qHqgvqwM5ieJHFcjn4MByzU/tLebHRc/ceuMqM78R5VfjcVNvEwWskmhAMvSH9jvPLvV91yMy5fuskg12jEkwMjjx2c7jcqbqg9epNKyX2zVYitBozEWhmwmxS543mfWcsBhvwvLRqMRtiFYnhU16LyjQkFCZBrYpBQiiZ4m5D0eTjjFXHBHnJN/kHLRZrC00du702stbG8+trpuy60cja0CDk0Unnss2EAyDhrr885LP4IRZzjSqvJV7+vxYTSX4L2QS2kyAXfLUcSebw7/lrtqx0sUeAo/jXQkvtFre6nZRYjWdHGo0CAwRc=

