FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .

#fix permissions for node_modules, for :  
# docker run -it -p 3000:3000 -v /app/node_modules -v ~/frontend:/app <IMAGE_ID>  
RUN chown -R node:node /app/node_modules
RUN chown node:node /app/node_modules

CMD ["npm", "run", "dev"]